{{- if and (not .Values.bomhort.existingSecret) .Values.bomhort.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vexviper.fullname" . }}
  labels: {{- include "vexviper.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-key: {{ .Values.bomhort.apiKey | quote }}
{{- end }}
